"""initial domain models

Revision ID: 392614d6779d
Revises: 
Create Date: 2026-08-29 22:26:10.525152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '392614d6779d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('before_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_table('cpse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('national_material',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('national_code', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('canonical_description', sa.Text(), nullable=False),
    sa.Column('valve_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=False),
    sa.Column('body_material', sa.String(length=100), nullable=False),
    sa.Column('pressure_class', sa.String(length=100), nullable=False),
    sa.Column('connection_type', sa.String(length=100), nullable=False),
    sa.Column('trim', sa.String(length=100), nullable=False),
    sa.Column('normalized_uom', sa.String(length=50), nullable=False),
    sa.Column('identity_key', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category = 'VALVE'", name='chk_national_material_category_valve'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_key'),
    sa.UniqueConstraint('national_code')
    )
    op.create_table('material',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cpse_id', sa.UUID(), nullable=False),
    sa.Column('source_material_code', sa.String(length=100), nullable=False),
    sa.Column('source_description', sa.Text(), nullable=False),
    sa.Column('source_uom', sa.String(length=50), nullable=False),
    sa.Column('source_specifications', sa.Text(), nullable=True),
    sa.Column('raw_source_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('valve_type', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('body_material', sa.String(length=100), nullable=True),
    sa.Column('pressure_class', sa.String(length=100), nullable=True),
    sa.Column('connection_type', sa.String(length=100), nullable=True),
    sa.Column('trim', sa.String(length=100), nullable=True),
    sa.Column('normalized_uom', sa.String(length=50), nullable=True),
    sa.Column('normalized_description', sa.Text(), nullable=True),
    sa.Column('normalized_attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("category IS NULL OR category = 'VALVE'", name='chk_material_category_valve'),
    sa.ForeignKeyConstraint(['cpse_id'], ['cpse.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpse_id', 'source_material_code', name='uq_material_cpse_source_code')
    )
    op.create_index('ix_material_category', 'material', ['category'], unique=False)
    op.create_index('ix_material_cpse_id', 'material', ['cpse_id'], unique=False)
    op.create_table('match_recommendation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_material_id', sa.UUID(), nullable=False),
    sa.Column('candidate_material_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("classification IN ('SAME', 'POTENTIALLY_EQUIVALENT', 'DIFFERENT')", name='chk_recommendation_classification'),
    sa.CheckConstraint('source_material_id != candidate_material_id', name='chk_recommendation_not_self'),
    sa.ForeignKeyConstraint(['candidate_material_id'], ['material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_material_id'], ['material.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_match_rec_candidate', 'match_recommendation', ['candidate_material_id'], unique=False)
    op.create_index('ix_match_rec_classification', 'match_recommendation', ['classification'], unique=False)
    op.create_index('ix_match_rec_source', 'match_recommendation', ['source_material_id'], unique=False)
    op.create_index('ix_match_rec_source_candidate', 'match_recommendation', ['source_material_id', 'candidate_material_id'], unique=False)
    op.create_table('material_national_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('material_id', sa.UUID(), nullable=False),
    sa.Column('national_material_id', sa.UUID(), nullable=False),
    sa.Column('basis', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('recommendation_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("basis IN ('AUTO_SAME', 'HUMAN_CONFIRMED_SAME', 'HUMAN_OVERRIDE')", name='chk_mapping_basis'),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUPERSEDED', 'INACTIVE')", name='chk_mapping_status'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['national_material_id'], ['national_material.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['match_recommendation.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_unique_active_mapping', 'material_national_mapping', ['material_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    op.create_index('ix_mapping_material_id', 'material_national_mapping', ['material_id'], unique=False)
    op.create_index('ix_mapping_national_material_id', 'material_national_mapping', ['national_material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_mapping_national_material_id', table_name='material_national_mapping')
    op.drop_index('ix_mapping_material_id', table_name='material_national_mapping')
    op.drop_index('idx_unique_active_mapping', table_name='material_national_mapping', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_table('material_national_mapping')
    op.drop_index('ix_match_rec_source_candidate', table_name='match_recommendation')
    op.drop_index('ix_match_rec_source', table_name='match_recommendation')
    op.drop_index('ix_match_rec_classification', table_name='match_recommendation')
    op.drop_index('ix_match_rec_candidate', table_name='match_recommendation')
    op.drop_table('match_recommendation')
    op.drop_index('ix_material_cpse_id', table_name='material')
    op.drop_index('ix_material_category', table_name='material')
    op.drop_table('material')
    op.drop_table('national_material')
    op.drop_table('cpse')
    op.drop_index('ix_audit_entity', table_name='audit_log')
    op.drop_index('ix_audit_created_at', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
